import { Header } from "@/components/Header/Header";
import { Menu } from "@/components/Menu/Menu";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Bash Learn",
  description: "Generated by create next app",
};

export default function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex justify-center w-full h-full bg-black">
      <Header />
      <main className="flex relative justify-between pt-[60px] max-w-[1380px] w-full min-h-screen border-white/20 border-x-1.5 border-dashed">
        <Menu />
        <div className="flex-1 w-full max-w-[924px]">
          {children}
        </div>
        <div className="w-[50px] md:block hidden h-[calc(100vh-60px)]">
        </div>
      </main>
    </div>
  );
}