import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import TranslationsProvider from '@/components/Provider/I18nProvider';

const poppinsFont = Poppins({
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={`${poppinsFont.variable} antialiase`}>
        <TranslationsProvider>
          {children}
        </TranslationsProvider>
      </body>
    </html>
  );
}
